# Generated by Django 4.2.6 on 2023-10-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='api_key',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
