# Generated by Django 4.2.6 on 2023-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbo', '0002_otp_api_key_alter_otp_email_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='api_key',
            field=models.CharField(default='', max_length=64),
        ),
    ]
